version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: anzorgreen/kittygram_backend
    container_name: backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: anzorgreen/kittygram_frontend
    container_name: fronend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    container_name: gateway
    image: anzorgreen/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/app/media

